apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: otel-test4
  description: otel-test4
  annotations:
    # mandatory annotation
    harness.io/project-url: https://app.harness.io/ng/#/account/GKaZCHFqTmqWZd874phqlw/home/orgs/FSG/projects/Experiandemo/
    # optional annotations, don't include this block if not needed. Add this if specific pipeline executions needs to be shown on the Plugin. When specified, latest pipeline execution details for configured pipelineIds(max 10) and configured serviceId will be shown.
  tags:
    - java

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
spec:
  type: service
  lifecycle: experimental
  owner: team-b
